version: '3.1'
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:15.0.2
    ports:
      # HOST:CONTAINER
      - "8081:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin